### ISSUE TITLE
[Feature Request] Tailwind CSS v2.0 support

### ISSUE THREAD

**Issue by mryurii** [creativetimofficial/notus-js#4]
### What is your enhancement?

Tailwind v2 released with batch of new and improved features. Any plans to to update UI kit to support it?

Related request - #3

**Comment by tuomohopia** [comment]
I wrote a PR for the upgrade: https://github.com/creativetimofficial/notus-js/pull/5

**Comment by tuomohopia** [comment]
@mryurii maybe you can help by trying if my upgrade PR works as expected on your end?

**Comment by EINazare** [comment]
Hello there, @mryurii @tuomohopia ,

Sorry for this late reply. I do not understand why Github did not notify me about this.
Yes, we'll update to Tailwind v2 in about 2 months.

Best,
Manu
